name: Continous Integration

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ devleop ]
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'


    - name: Build with Gradle
      run: gradle build
    - name: Code Coverage
      uses: codecov/codecov-action@v1.0.6
      with:
        token: ${{ 654b64f1-1764-4568-b3ab-d2a4c4816463 }}


