name: Continous Integration

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'


    - name: Build with Gradle
      run: gradle build
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: run codecov
        run: gradle build jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: UML/coverage/test/jacocoTestReport.xml
          name: codecov-umbrella
          fail_ci_if_error: true

